<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'SovereignApplication' => 'sovereign/application/SovereignApplication.php',
    'SovereignBaseController' => 'sovereign/controller/SovereignBaseController.php',
    'SovereignController' => 'sovereign/controller/SovereignController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'SovereignApplication' => 'PhabricatorApplication',
    'SovereignBaseController' => 'PhabricatorController',
    'SovereignController' => 'SovereignBaseController',
  ),
));
